language: python
dist: xenial
cache: pip
env:
    matrix:
        - COVERALLS=true

install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade -r requirements-test.txt
    - pip install --upgrade .
before_script:
    - pytest --version
script:
    - pytest -vv --cov
after_success:
    - if [[ ${COVERALLS} == true ]]; then coveralls; fi

jobs:
    fast_finish: true
    allow_failures:
        - python: "2.7"
        - python: "3.5-dev"
        - python: "3.6-dev"
        - python: "3.7-dev"
        - python: "3.8-dev"
    include:
        - python: "2.7"
        - python: "3.5"
        - python: "3.5-dev"
        - python: "3.6"
        - python: "3.6-dev"
        - python: "3.7"
        - python: "3.7-dev"
        - python: "3.8-dev"
          env: COVERALLS=false

        - stage: pylint
          python: "3.7"
          addons: skip
          install:
            - pip install --upgrade -r requirements-test.txt
          script:
            - python run_pylint.py --disable=fixme --fail-under=9.5 pysmiles
          after_success: skip
